Server:
  Port: 5005
  RunMode: debug
Logger: 
  Filepath: ../logs/logs.log
  Encoding: json
  Level: debug
  Logger: zerolog
Cors: 
  AllowOrigins: "*"
Postgres: 
  Host: localhost
  Port: 5432
  User: postgres
  PassWord: admin
  dbName: car_sale_db
  sslMode: disable
  MaxIdleConns: 15
  SetMaxOpenConns: 100
  SetConnMaxLifetime: 5
redis: 
  Host: localhost
  Port: 6379
  PassWord: password
  db: 0
  minIdleconnections: 100
  pollsize: 5000
  poolTimeout: 240
otp:
  expireTime: 120
  digits: 6
  limiter: 100
