definitions:
  github_com_AmirHosein-Kahrani_Car-Center-Web_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_AmirHosein-Kahrani_Car-Center-Web_api_validations.ValidationErrors'
        type: array
    type: object
  github_com_AmirHosein-Kahrani_Car-Center-Web_api_validations.ValidationErrors:
    properties:
      Property:
        type: string
      message:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  src_api_handlers.PersonData:
    properties:
      first_name:
        maxLength: 10
        minLength: 4
        type: string
      last_name:
        maxLength: 20
        minLength: 6
        type: string
      mobile_number:
        type: string
    required:
    - first_name
    - last_name
    - mobile_number
    type: object
info:
  contact: {}
paths:
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_AmirHosein-Kahrani_Car-Center-Web_api_helper.BaseHttpResponse'
      tags:
      - Health
  /v1/test/binder/body:
    post:
      consumes:
      - application/json
      description: BodyBinder
      parameters:
      - description: person data
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/src_api_handlers.PersonData'
      produces:
      - application/json
      responses:
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_AmirHosein-Kahrani_Car-Center-Web_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      tags:
      - Test
  /v1/test/user/{id}:
    get:
      consumes:
      - application/json
      description: UserById
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_AmirHosein-Kahrani_Car-Center-Web_api_helper.BaseHttpResponse'
      tags:
      - Test
swagger: "2.0"
